### ISSUE TITLE
Support `repeated` fields 

### ISSUE THREAD

**Issue by lucasvo** [centrifuge/precise-proofs#10]
We should add support for repeated fields to the Merkle tree generation. The `FlattenMessage` method needs to be extended as follows:

```proto,
message Example {
    repeated string list_field = 1;
}
```

```go,
// FlattenMessage should create the following LeafNodes (pseudo code)
example := Example{ListField:[]string{"A", "B", "C"}
tree.FlattenMessage(example)
// Creates properties (Property, Value)
"list_field.length", 3
"list_field[0]", "A"
"list_field[1]", "B"
"list_field[2]", "C"
```

In addition we need to update FillSalts to check the length of the specified field and add length + 1 items to the corresponding list in the salts protobuf message. (+1 because the length item in the tree also needs a salt).

**Comment by lucasvo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [List/repeated fields support in precise-proofs](https://trello.com/c/ydHvtCwk/207-list-repeated-fields-support-in-precise-proofs)

**Comment by mikiquantum** [comment]
Being done here: https://github.com/centrifuge/precise-proofs/pull/18
