### ISSUE TITLE
Exclude/Include protobuf properties

### ISSUE THREAD

**Issue by lucasvo** [centrifuge/precise-proofs#11]
Supporting a standardized way to exclude certain properties from a merkle tree would be great. We could leverage protobuf options but there is no consistent way to get the extra tags into generated bindings for Go (and other languages). 

An option would be the following project: https://github.com/favadi/protoc-go-inject-tag

We could then change FlattenMessage to look for these tags and skip the fields matching a tag. Alternatively we could add an extra argument to FlattenMessage for a white/black list of fields. This is not optimal however because it is then this part of the "schema" lives outside of the .proto file and would have to be maintained separately.

**Comment by pstehlik** [comment]
I would go for the tags to keep in one file (as you suggest) and actually whitelist via a tag - instead of blacklist the fields to exclude.
Then it is really explicit about what will be included and avoid the scenario where something gets added "on accident".

**Comment by lucasvo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Implement feature to ignore fields in precise-proofs](https://trello.com/c/sy8K3ZwZ/133-implement-feature-to-ignore-fields-in-precise-proofs)

**Comment by lucasvo** [comment]
> Then it is really explicit about what will be included and avoid the scenario where something gets added "on accident".

Well, with an exclude list, you can avoid accidentally leaving something out... I prefer excludes because for our use case (or implement both - should be trivial).

**Comment by lucasvo** [comment]
We really need to look at how a tag would be implemented in another language though, precise-proofs needs to be something that can also work in other languages.

**Comment by pstehlik** [comment]
Yes on looking at tags for other languages.  However, if not possible to react on tags in another language one could resort back to having a script that parses the tags and creates an external whitelist from the tags first and then have the other language utilize that list separately.

I strongly disagree with the blacklisting comment. If a developer adds a field they will write tests to make sure that this field actually shows up. And they will test if this new field works. Worst-case they forget to add a tag, test, and then see that they forgot to add a tag. Then go back and add the tag.
The other way around is not so safe: someone might add a field for their use-case but forget to explicitly exclude the field. The likelihood that this mistake is caught is much lower and could lead to unwanted side-effects later on in the tree and proof generation with other things breaking without knowing exactly why. The debugging will most likely be more cumbersome.
