### ISSUE TITLE
Change Merkle tree to order hashes

### ISSUE THREAD

**Issue by lucasvo** [centrifuge/precise-proofs#14]
Given a tree with two leaves (A, B) we can calculate the parent node in two ways:

```python,
# Unsorted
hashA = H(A)
hashB = H(B)
parentHash = Hash(hashA+hashB)

# Sorted leaves:
hashA = H(A)
hashB = H(B)
if hashA > hashB:
    parentHash = Hash(hashB+hashA)
else: 
    parentHash = Hash(hashA+hashB)
``` 

Comparing the two ways to construct a tree, there are advantages and disadvantages. Unsorted trees require you to submit not just a list of hashes in a Merkle proof but also of they are the left or the right node in the path so that the verification can correctly concatenate the hash. This allows you to know the position of a node in the tree. You can deduce the index of the leaf by looking at how the proof is constructed. This can be an advantage when you care about proving the position of an item in a set not just the fact that it is present in the set. For our precise proofs which generally can have dynamic lengths (because the number of items depends on things such as dynamic length fields on messages) the position in the tree doesn't say a whole lot so we don't actually need to care about the position in the tree. By making our trees order the two inputs to the hash function we can simplify the format of the proof to just contain a list of hashes. This is cheaper store/validate on chain. Instead of storing 256bit hash + 1 bit left/right bool a simple list of 256bit hashes is enough. 

An example verifier is implemented by OpenZeppelin with the sorted tree style:
https://github.com/OpenZeppelin/openzeppelin-solidity/blob/master/contracts/MerkleProof.sol

**Comment by mikiquantum** [comment]
Merged: https://github.com/centrifuge/go-merkle/pull/1 and https://github.com/centrifuge/precise-proofs/pull/16
