### ISSUE TITLE
Why would we want two ways of creating/sorting the trees?

### ISSUE THREAD

**Issue by pstehlik** [centrifuge/precise-proofs#17]
Looking at [the option to sort the tree](https://github.com/centrifuge/precise-proofs/blob/9e2d12f6dd1023e98d729d9fa94083482018bd2c/proofs/tree.go#L55) I wonder why would we want to have this as an option and not rather as the default/only implementation?

If we want to promote a standard way to create the proofs where the standard can traverse project boundaries, introducing the options in how to process the data is making it harder to have easy compatibility later on.

Maybe I am missing the point here why we introduce a flag instead of changing the base-implementation.

**Comment by mikiquantum** [comment]
My understanding of the precise-proof public library is that will not only be used by our merkling of documents but as for anyone that wants to generate merkle trees for proofs.

There are some differences on how to identify a node within the tree that we cannot ensure with the sorted hashes implementation that might be of use case for other users that not necessarily use the library on their code to interact with our documents.

In the go-centrifuge project we will make it clear that we use the sortedhash implementation.
