### ISSUE TITLE
Support for nested documents

### ISSUE THREAD

**Issue by vimukthi-git** [centrifuge/precise-proofs#6]
Hi @lucasvo ,

I have a question regarding `support for nested documents` which I thought may be I could help in implementing. Apologies if creating an issue is not the correct way to reach you for this.

Question:
Do you have an idea/design on how go about implementing this? 
My initial idea is that this can be implemented by making `FlattenMessage` recursively go through each struct its encounters in the protobuf message and apply the same sorting algorithm to nested properties. In addition to this `FlattenMessage` can apply dot notation to `LeafNode.Property` to correctly identify the field.
I see that you have made comments on some other functions that needs to be modified in order to complete support for nested structures. 

Thanks.

**Comment by lucasvo** [comment]
The option you're proposing is one of two I am thinking about right now. The alternative would be to create a merkle tree for any nested structure (an embedded object or a list of values). This has a slight security advantage: the length of the merkle proof stays the same for any first-level properties. You can only deduct any information from the length of the proof if the proof is for a nested/array field. If you'd just prove a sibling node, the length of it's proof would stay constant. 

The implementation however is a bit more complicated, essentially the LeafNode would either contain a value or another embedded tree and picking the leaves for a proof would have to support traversing these nested trees. 

I'll update this issue with more details when I get to it

**Comment by vimukthi-git** [comment]
I think your alternative structure makes sense from application modelling perspective as well, Since this would provide a way to sensibly link documents/objects that are related instead of embedding all related entities in one message. However this might enable second preimage attack vector where the attacker can embed a merkle tree with a root hash that could prove arbitrary values to be part of the base merkle tree.
Anyways I will await your feedback on this once you reach that point. Thanks.

**Comment by lucasvo** [comment]
Valid concern but it's not a problem if the format of the leaf nodes that can be proven in the tree are of a specific format. Because leaf nodes are always of this format: `H(property,value,salt)` a second preimage attack is not an issue because any easily found second preimage would not match that format.

**Comment by lucasvo** [comment]
I've specified what needs to be done to properly support repeated fields over at #10 The changes will be pretty similar for this issue.

Example protobuf: 
```proto,
message Foobar {
    string foo = 1;
    string bar = 2;
}
message Example {
    Foobar foobar = 1;
    repeated Foobar foos = 2;
}
```

```go,
// FlattenMessage should create the following LeafNodes (pseudo code)
example := Example{
     foobar: &Foobar{foo:"1", bar:"2"}, 
    foos: []Foobar{
         &Foobar{foo:"widget", bar:"gadget"},
    }
}
tree.FlattenMessage(example)
// Creates properties (Property, Value)
"foobar.foo", "1"
"foobar.bar", "2"
"foos.length", "1"
"foos[0].foo", "widget"
"foos[0].bar", "gadget"
```
In addition the FillSalts needs to be adjusted to create instances of FoobarSalts for each embedded document and fill it as well.
