### ISSUE TITLE
i can't find "GenerateByTwoHashFunc" func in go-merkle

### ISSUE THREAD

**Issue by gyley** [centrifuge/precise-proofs#89]
i can't find "GenerateByTwoHashFunc" func in go-merkle,which is used by file "tree.go" at line 570.
vendor\github.com\centrifuge\precise-proofs\proofs\tree.go:570:27: doctree.merkleTree.GenerateByTwoHashFunc undefined (type merkle.Tree has no field or method GenerateByTwoHashFunc)

**Comment by lucasvo** [comment]
@mikiquantum I think you last touched this, do you know why?

**Comment by mikiquantum** [comment]
@gyley we are forking the original xleonard/go-merkle and added functions that we need on top: https://github.com/centrifuge/precise-proofs/blob/master/Gopkg.toml#L39

**Comment by gyley** [comment]
@mikiquantum i get，thank q
